# Generated by Django 3.0.6 on 2020-05-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_auto_20200521_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='roomM1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomM2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomM3',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomM4',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomM5',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomM6',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomT1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomT2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomT3',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomT4',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomT5',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomT6',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomW1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomW2',
            field=models.CharField(max_length=5),
        ),
    ]
