# Generated by Django 3.0.6 on 2020-05-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0003_auto_20200522_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='roomF1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomF2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomF3',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomF4',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomF5',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomF6',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomTH1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomTH2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomTH3',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomTH4',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomTH5',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomTH6',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomW3',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomW4',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomW5',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='roomW6',
            field=models.CharField(max_length=5),
        ),
    ]
